application: thaiinhk
version: dev
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "14d"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^test/(.*/)?
- ^COPYING.LESSER
- ^README\..*
- \.gitignore
- ^\.git/.*
- ^Makefile
- ^requirements\.txt
- \.ropeproject

builtins:
- remote_api: on 

handlers:

- url: /static
  static_dir: static 
  http_headers:
      Vary: Accept-Encoding

- url: /images
  static_dir: images 

- url: /favicon\.ico
  mime_type: image/vnd.microsoft.icon
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /apple-touch-icon\.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png

- url: /apple-touch-icon-precomposed\.png
  static_files: static/apple-touch-icon-precomposed.png
  upload: static/apple-touch-icon-precomposed.png

- url: /(robots\.txt|humans\.txt|crossdomain\.xml)
  static_files: static/\1
  upload: static/(robots\.txt|humans\.txt|crossdomain\.xml)

- url: /api/.*
  script: main.api_app
  #http_headers:
      #Access-Control-Allow-Origin: "*"

- url: /mail/.*
  script: main.admin_app
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
